version: 0.0
os: linux
files:
  - source: src/main/resources/templates/index.html
    destination: /
hooks:
  BeforeInstall:
    - location: deploy/before_install/before_start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server/after_start.sh
      timeout: 300
      runas: root
